Repository inngest/inngest, pull requests merged in 2024-02, with the labels that each got.

#927 Improve fetching when toggling internal event visibility
  ui/apps/dev-server-ui/src/app/(dashboard)/stream/Stream.tsx
Labels: area/dev-server

#1083 Fix history not extracting and using invocation outputs for timeline
  pkg/execution/execution.go
  pkg/execution/history/lifecycle.go
Labels: bug

#1140 Add a small example to the middleware docs overview
  ui/apps/website/pages/docs/reference/middleware/overview.mdx
Labels: documentation

#1144 Remove buttons for removing org memberships and user accounts tempora…
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/settings/organization/[[...organization]]/page.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/settings/user/[[...user]]/page.tsx
Labels: cloud-ui

#1129 INN-2769 On `step.invoke()` timeouts, set an error in state stores
  pkg/execution/execution.go
  pkg/execution/executor/executor.go
  pkg/execution/executor/service.go
Labels: feature
