Repository inngest/inngest, pull requests merged in 2024-03, with the labels that each got.

#1207 Fix missing running state in Dev Server UI
  go.mod
  pkg/coreapi/generated/generated.go
  pkg/coreapi/gql.schema.graphql
  pkg/coreapi/gqlgen.yml
  pkg/coreapi/graph/models/models_gen.go
  pkg/coreapi/graph/resolvers/event.resolver.go
  pkg/coreapi/graph/resolvers/function_run.resolver.go
  pkg/coreapi/graph/resolvers/functions.go
  pkg/coreapi/graph/resolvers/stream.go
  pkg/history_drivers/memory_writer/writer.go
  ui/apps/dev-server-ui/src/app/(dashboard)/stream/useEvent.ts
  ui/apps/dev-server-ui/src/app/(dashboard)/stream/useRun.ts
  ui/apps/dev-server-ui/src/coreapi.ts
  ui/apps/dev-server-ui/src/store/generated.ts
Labels: area/dev-server

#1203 INN-2843 Add `Triggerable` concept to OSS to help `inngestgo` with multi-trigger
  pkg/inngest/trigger.go
Labels: go

#1205 Duplicate syncs
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/apps/AppCard.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/apps/[externalID]/syncs/Sync/Sync.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/apps/[externalID]/syncs/SyncList.tsx
  ui/apps/dashboard/src/components/AppInfoCard/AppInfoCard.tsx
  ui/apps/dashboard/src/components/SyncStatus.tsx
  ui/apps/dashboard/src/components/SyncStatusPill.tsx
  ui/packages/components/src/icons/Duplicate.tsx
  ui/packages/components/src/types/sync.ts
Labels: dev-server-ui

#1209 Clarify some points about the signing key and signature
  docs/SDK_SPEC.md
Labels: documentation

#1212 Fix missing run status in event details
  pkg/coreapi/graph/models/converters.go
Labels: dev-server-ui

#1217 Redirect to stream on event/run fetch error
  ui/apps/dev-server-ui/src/app/(dashboard)/stream/StreamDetails.tsx
Labels: dev-server-ui

#1225 Move `<Alert>` to the shared component library
  ui/apps/dashboard/src/app/(auth)/sign-in/[[...sign-in]]/page.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/apps/[externalID]/ResyncModal.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/apps/[externalID]/layout.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/apps/[externalID]/syncs/Sync/Sync.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/events/[eventName]/SendEventModal.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/events/[eventName]/page.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/functions/[slug]/(dashboard)/page.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/functions/[slug]/InvokeButton/InvokeModal.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/functions/error.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/manage/signing-key/page.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/settings/billing/BillableStepUsage/BillableStepUsage.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/settings/billing/CheckoutModal.tsx
  ui/apps/dashboard/src/app/(organization-active)/intent/ApprovalDialog.tsx
  ui/apps/dashboard/src/app/(organization-active)/support/SupportForm.tsx
  ui/apps/dashboard/src/components/SyncFailure/SyncFailure.tsx
  ui/packages/components/src/Alert/Alert.stories.tsx
  ui/packages/components/src/Alert/Alert.tsx
  ui/packages/components/src/Alert/index.ts
Labels: cloud-ui, dev-server-ui

#1224 Hide replay buttons for internal events
  ui/packages/components/src/EventDetails/EventDetails.tsx
Labels: bug

#1226 INN-2806 Add "Invoke" button to triggers in Dev Server
  pkg/coreapi/coreapi.go
  pkg/coreapi/generated/generated.go
  pkg/coreapi/gql.mutations.graphql
  pkg/coreapi/graph/resolvers/app_mutations.go
  pkg/coreapi/graph/resolvers/resolver.go
  pkg/devserver/devserver.go
  pkg/devserver/service.go
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/functions/[slug]/InvokeButton/InvokeButton.tsx
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/functions/[slug]/InvokeButton/index.ts
  ui/apps/dashboard/src/app/(organization-active)/(dashboard)/env/[environmentSlug]/functions/[slug]/layout.tsx
  ui/apps/dev-server-ui/src/app/(dashboard)/functions/page.tsx
  ui/apps/dev-server-ui/src/coreapi.ts
  ui/apps/dev-server-ui/src/store/generated.ts
  ui/packages/components/src/InvokeButton/InvokeButton.tsx
  ui/packages/components/src/InvokeButton/InvokeModal.tsx
  ui/packages/components/src/InvokeButton/index.ts
Labels: javascript, go, cloud-ui, dev-server-ui

#1238 INN-2879 Fix Dev Server ingestion returning external IDs
  pkg/api/service.go
  pkg/devserver/devserver.go
  pkg/devserver/service.go
  pkg/event/event.go
  pkg/event/mgr_legacy.go
  pkg/execution/executor/service.go
  pkg/execution/runner/runner.go
Labels: bug
